using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Vendas.Api.Models.Enums;

namespace Vendas.Api.Models
{
    public class SaborConfiguration : IEntityTypeConfiguration<Sabor>
    {
        public void Configure(EntityTypeBuilder<Sabor> builder)
        {
            builder.
                 ToTable("sabor");
            builder.HasKey(x => x.Id);
            builder.HasData(new Sabor { Id = 1, Titulo = "Mussarela", Descricao = "Mussarela e azeitonas", Tag = "queijo", ValorAdicional = 0, Tipo = (int)TipoProduto.Pizza },
     new Sabor { Id = 2, Titulo = "Napolitana", Descricao = "Mussarela, fatias de tomate e parmesão", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 3, Titulo = "Marguerita", Descricao = "Mussarela, tomate, manjericão fresco e parmesão", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 4, Titulo = "Marguerita com Peperone", Descricao = "Mussarela, fatias de tomate, peperone, manjericão e parmesão", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 5, Titulo = "Catupiry Legítimo", Descricao = "Catupiry legítimo e azeitonas", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 6, Titulo = "2 Queijos", Descricao = "Mussarela e catupiry legítimo", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 7, Titulo = "3 Queijos", Descricao = "Mussarela, catupiry legítimo e provolone", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 8, Titulo = "4 Queijos", Descricao = "Mussarela, catupiry legítimo, provolone e parmesão", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 9, Titulo = "5 Queijos", Descricao = "Mussarela, catupiry legítimo, provolone, parmesão e gorgonzola", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 10, Titulo = "Pomodoro", Descricao = "Mussarela, parmesão e alho frito", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Pizza },

     new Sabor { Id = 11, Titulo = "Frango com Mussarela", Descricao = "Frango, milho e mussarela", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 12, Titulo = "Frango com Catupiry", Descricao = "Frango temperado com catupiry legítimo", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 13, Titulo = "Frango com Provolone", Descricao = "Frango temperado, bacon frito e provolone", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 14, Titulo = "Caipira", Descricao = "Filé de frango temperado, milho no vapor e catupiry legítimo", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 15, Titulo = "Carijó", Descricao = "Frango, milho, ervilha e mussarela", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 16, Titulo = "Jardineira", Descricao = "Frango, bacon frito e mussarela", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 17, Titulo = "Frango Especial", Descricao = "Frango, bacon, palmito, tomate, catupiry e mussarela", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Pizza },

     new Sabor { Id = 18, Titulo = "Baiana", Descricao = "Calabresa moída, pimenta, ovos cozidos e cebola", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 19, Titulo = "Baiana Especial", Descricao = "Calabresa moída, tomate, cebola e parmesão", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 20, Titulo = "Calabresa", Descricao = "Calabresa fatiada, cebola e azeitonas", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 21, Titulo = "Calabresa com Mussarela", Descricao = "Calabresa fatiada e mussarela", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 22, Titulo = "Calabresa com Catupiry Legítimo", Descricao = "Calabresa fatiada, cebola e catupiry legítimo", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 23, Titulo = "Toscana", Descricao = "Calabresa moída e mussarela", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 24, Titulo = "Toscana Especial", Descricao = "Calabresa moída, ovos cozidos, cebola e mussarela", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Pizza },

     new Sabor { Id = 25, Titulo = "Atum", Descricao = "Atum sólido, cebola e azeitonas", Tag = "peixe", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 26, Titulo = "Atum com Catupiry Legítimo", Descricao = "Atum sólido, cebola, tomate e catupiry legítimo", Tag = "peixe", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 27, Titulo = "Atum com Mussarela", Descricao = "Atum sólido, cebola, tomate e mussarela", Tag = "peixe", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 28, Titulo = "Brasileira", Descricao = "Atum sólido, bacon, cebola, ovos cozidos e mussarela", Tag = "peixe", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 29, Titulo = "Americana", Descricao = "Atum sólido, palmito e mussarela", Tag = "peixe", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
     new Sabor { Id = 30, Titulo = "Espanhola", Descricao = "Atum sólido, palmito, ervilha e mussarela", Tag = "peixe", ValorAdicional = 0, Tipo = TipoProduto.Pizza },

    new Sabor { Id = 31, Titulo = "Bella Castelli", Descricao = "Brócolis, atum e cobertura de mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 32, Titulo = "Tomate Seco", Descricao = "Mussarela de búfala, tomate seco e rúcula", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 33, Titulo = "Rúcula", Descricao = "Mussarela, tomate seco e rúcula", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 34, Titulo = "Peperone", Descricao = "Mussarela, peperone Sadia e parmesão", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 35, Titulo = "Brócolis", Descricao = "Brócolis, bacon e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 36, Titulo = "Brócolis com Catupiry Legítimo", Descricao = "Brócolis, palmito e catupiry legítimo", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 37, Titulo = "Champignon", Descricao = "Champignon temperado, bacon e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 38, Titulo = "Carne Seca", Descricao = "Carne seca, tomate, cebola e mussarela com toque de pimenta biquinho", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 39, Titulo = "Escarola com Bacon", Descricao = "Escarola, bacon e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 40, Titulo = "Doce de Cid", Descricao = "Mussarela, abacaxi em calda, hortelã e toque de canela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 41, Titulo = "Escarola Especial", Descricao = "Escarola, palmito, tomate, alho e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 42, Titulo = "Alho", Descricao = "Molho de tomate, parmesão e alho frito", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 43, Titulo = "Milho com Mussarela", Descricao = "Milho coberto com mussarela e orégano", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 44, Titulo = "Milho com Catupiry Legítimo", Descricao = "Milho coberto com catupiry legítimo", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 45, Titulo = "Palmito", Descricao = "Palmito fatiado com cobertura de mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },

    new Sabor { Id = 46, Titulo = "Siciliana", Descricao = "Champignon temperado, bacon, mussarela e alho frito", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 47, Titulo = "À Moda da Casa", Descricao = "Calabresa moída, frango, tomate e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 48, Titulo = "Portuguesa", Descricao = "Presunto, ovos cozidos, ervilhas, cebola e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 49, Titulo = "Paulista", Descricao = "Presunto, palmito, pimentão, cebola e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 50, Titulo = "Cowboy", Descricao = "Presunto, ovos cozidos, bacon e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 51, Titulo = "Do Pizzaiolo", Descricao = "1/4 Calabresa, 1/4 Mussarela, 1/4 Frango com catupiry e 1/4 Portuguesa", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 52, Titulo = "Bauru", Descricao = "Presunto, tomate e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 53, Titulo = "Calabria", Descricao = "Calabresa fatiada, bacon, ovos, tomate e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 54, Titulo = "Aliche", Descricao = "Molho de tomate, selecionado, parmesão e azeitonas", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 55, Titulo = "Bacon I", Descricao = "Bacon frito e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 56, Titulo = "Bacon II", Descricao = "Presunto, ovos, cebola e bacon", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 57, Titulo = "Italiana", Descricao = "Presunto canadense, bacon e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 58, Titulo = "Lombo com Mussarela", Descricao = "Lombo tipo canadense e mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 59, Titulo = "Lombo com Catupiry", Descricao = "Lombo tipo canadense e catupiry legítimo", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 60, Titulo = "Padrão", Descricao = "Lombo tipo canadense, bacon, milho e provolone", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 61, Titulo = "Peruana", Descricao = "Peito de peru, bacon frito, azeitonas e catupiry legítimo", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 62, Titulo = "Peruana com Mussarela", Descricao = "Peito de peru, tomate, mussarela", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 63, Titulo = "Francesa", Descricao = "Peito de peru, palmito, cebola e catupiry legítimo", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 64, Titulo = "Abobrinha", Descricao = "Abobrinha, mussarela e alho frito", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 65, Titulo = "Abobrinha Especial", Descricao = "Abobrinha, alho poró, parmesão e cream cheese", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 66, Titulo = "Brócolis Especial", Descricao = "Brócolis, bacon, cebola e cream cheese", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 67, Titulo = "Philadelphia", Descricao = "Peito de peru e cream cheese", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 68, Titulo = "Frango c/ Cream Cheese", Descricao = "Frango, bacon e cream cheese", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 69, Titulo = "Filé Mignon", Descricao = "Filé mignon, mussarela, cebola, catupiry e alho frito salpicado", Tag = "especial", ValorAdicional = 0, Tipo = TipoProduto.Pizza },

    new Sabor { Id = 80, Titulo = "Morango", Descricao = "Morango, chocolate e leite condensado", Tag = "doce", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 81, Titulo = "Banana", Descricao = "Chocolate, banana com canela e leite condensado", Tag = "doce", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 82, Titulo = "Banana com Chocolate", Descricao = "Chocolate, banana, canela e leite condensado", Tag = "doce", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 83, Titulo = "Chocolate", Descricao = "Chocolate e granulado", Tag = "doce", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 84, Titulo = "Nutella", Descricao = "Nutella, castanha ou frutas (morango ou banana)", Tag = "doce", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 85, Titulo = "Nutella com MM’s", Descricao = "Nutella e M&M’s", Tag = "doce", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 86, Titulo = "Chocolate com MM’s", Descricao = "Chocolate e M&M’s", Tag = "doce", ValorAdicional = 0, Tipo = TipoProduto.Pizza },
    new Sabor { Id = 87, Titulo = "Nutella com Castanha", Descricao = "Nutella com castanha", Tag = "doce", ValorAdicional = 0, Tipo = TipoProduto.Pizza },

    //esfilha
    new Sabor { Id = 88, Titulo = "Carne", Descricao = "Esfiha aberta de carne temperada", Tag = "carne", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 89, Titulo = "Queijo", Descricao = "Esfiha aberta com queijo derretido", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 90, Titulo = "Calabresa", Descricao = "Calabresa fatiada e levemente apimentada", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 91, Titulo = "Frango com Catupiry", Descricao = "Frango desfiado com catupiry cremoso", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 92, Titulo = "Bauru", Descricao = "Presunto, queijo e tomate", Tag = "presunto", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 93, Titulo = "Atum", Descricao = "Atum temperado com leve toque de limão", Tag = "atum", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 94, Titulo = "Atum com Queijo", Descricao = "Atum temperado e queijo derretido", Tag = "atum", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 95, Titulo = "Palmito com Queijo", Descricao = "Palmito picado com queijo", Tag = "palmito", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 96, Titulo = "Palmito com Catupiry", Descricao = "Palmito com catupiry cremoso", Tag = "palmito", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 97, Titulo = "Escarola com Queijo", Descricao = "Escarola refogada com queijo", Tag = "vegetariana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 98, Titulo = "Calabresa com Queijo", Descricao = "Calabresa e queijo derretido", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 99, Titulo = "Calabresa com Catupiry", Descricao = "Calabresa com catupiry cremoso", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 100, Titulo = "Milho com Queijo", Descricao = "Milho verde com queijo derretido", Tag = "vegetariana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 101, Titulo = "Milho Catupiry", Descricao = "Milho verde com catupiry", Tag = "vegetariana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 102, Titulo = "Bacon com Queijo", Descricao = "Bacon crocante e queijo derretido", Tag = "bacon", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 103, Titulo = "Dois Queijos", Descricao = "Mistura de queijos derretidos", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 104, Titulo = "Carne com Queijo", Descricao = "Carne temperada com queijo", Tag = "carne", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 105, Titulo = "Brócolis com Queijo", Descricao = "Brócolis refogado com queijo", Tag = "vegetariana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 106, Titulo = "Pepperone", Descricao = "Pepperone levemente picante com queijo", Tag = "pepperone", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 107, Titulo = "Carne Seca com Queijo", Descricao = "Carne seca desfiada com queijo", Tag = "carne", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 108, Titulo = "Carne Seca com Catupiry", Descricao = "Carne seca desfiada com catupiry", Tag = "carne", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 109, Titulo = "Catupiry", Descricao = "Esfiha aberta apenas com catupiry", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 88, Titulo = "Carne", Descricao = "Esfiha aberta de carne temperada", Tag = "carne", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 89, Titulo = "Queijo", Descricao = "Esfiha aberta com queijo derretido", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 90, Titulo = "Calabresa", Descricao = "Calabresa fatiada e levemente apimentada", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 91, Titulo = "Frango com Catupiry", Descricao = "Frango desfiado com catupiry cremoso", Tag = "frango", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 92, Titulo = "Bauru", Descricao = "Presunto, queijo e tomate", Tag = "presunto", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 93, Titulo = "Atum", Descricao = "Atum temperado com leve toque de limão", Tag = "atum", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 94, Titulo = "Atum com Queijo", Descricao = "Atum temperado e queijo derretido", Tag = "atum", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 95, Titulo = "Palmito com Queijo", Descricao = "Palmito picado com queijo", Tag = "palmito", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 96, Titulo = "Palmito com Catupiry", Descricao = "Palmito com catupiry cremoso", Tag = "palmito", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 97, Titulo = "Escarola com Queijo", Descricao = "Escarola refogada com queijo", Tag = "vegetariana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 98, Titulo = "Calabresa com Queijo", Descricao = "Calabresa e queijo derretido", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 99, Titulo = "Calabresa com Catupiry", Descricao = "Calabresa com catupiry cremoso", Tag = "calabresa", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 100, Titulo = "Milho com Queijo", Descricao = "Milho verde com queijo derretido", Tag = "vegetariana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 101, Titulo = "Milho Catupiry", Descricao = "Milho verde com catupiry", Tag = "vegetariana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 102, Titulo = "Bacon com Queijo", Descricao = "Bacon crocante e queijo derretido", Tag = "bacon", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 103, Titulo = "Dois Queijos", Descricao = "Mistura de queijos derretidos", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 104, Titulo = "Carne com Queijo", Descricao = "Carne temperada com queijo", Tag = "carne", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 105, Titulo = "Brócolis com Queijo", Descricao = "Brócolis refogado com queijo", Tag = "vegetariana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 106, Titulo = "Pepperone", Descricao = "Pepperone levemente picante com queijo", Tag = "pepperone", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 107, Titulo = "Carne Seca com Queijo", Descricao = "Carne seca desfiada com queijo", Tag = "carne", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 108, Titulo = "Carne Seca com Catupiry", Descricao = "Carne seca desfiada com catupiry", Tag = "carne", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 109, Titulo = "Catupiry", Descricao = "Esfiha aberta apenas com catupiry", Tag = "queijo", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 110, Titulo = "Chocolate com Granulado", Descricao = "Chocolate cremoso com granulado", Tag = "chocolate", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 111, Titulo = "Chocolate com Morango", Descricao = "Chocolate com pedaços de morango", Tag = "chocolate", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 112, Titulo = "Chocolate com Banana", Descricao = "Chocolate com rodelas de banana", Tag = "chocolate", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 113, Titulo = "Nutella", Descricao = "Esfiha doce recheada com Nutella", Tag = "nutella", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 114, Titulo = "Nutella com M&M's", Descricao = "Nutella com cobertura de M&M's", Tag = "nutella", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 115, Titulo = "Chocolate com M&M's", Descricao = "Chocolate cremoso com M&M's", Tag = "chocolate", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 116, Titulo = "Banana com Leite Condensado", Descricao = "Banana com cobertura de leite condensado", Tag = "banana", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 117, Titulo = "Chocolate com Castanha", Descricao = "Chocolate com pedaços de castanha", Tag = "chocolate", ValorAdicional = 0, Tipo = TipoProduto.Esfiha },
    new Sabor { Id = 118, Titulo = "Nutella com Castanha", Descricao = "Nutella com castanhas crocantes", Tag = "nutella", ValorAdicional = 0, Tipo = TipoProduto.Esfiha });

        }
    }
}
