// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vendas.Api.Database;

#nullable disable

namespace Vendas.Api.Migrations
{
    [DbContext(typeof(VendasDbContext))]
    [Migration("20250515004758_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vendas.Api.Models.Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titulo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("adicional", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Borda Catupiry",
                            Titulo = "Borda",
                            Valor = 2m
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Borda Cream Cheese",
                            Titulo = "Borda",
                            Valor = 2m
                        },
                        new
                        {
                            Id = 3,
                            Tipo = "Borda Cheedar",
                            Titulo = "Borda",
                            Valor = 2m
                        });
                });

            modelBuilder.Entity("Vendas.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Vendas.Api.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Forma")
                        .HasColumnType("int");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("pagamento", (string)null);
                });

            modelBuilder.Entity("Vendas.Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("clienteId");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("observacao");

                    b.Property<int>("PagamentoId")
                        .HasColumnType("int")
                        .HasColumnName("pagamentoId");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PagamentoId");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("Vendas.Api.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("observacao");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("pedidoId");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produtoId");

                    b.Property<int>("TamanhoId")
                        .HasColumnType("int")
                        .HasColumnName("tamanhoId");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TamanhoId");

                    b.ToTable("pedidoItem", (string)null);
                });

            modelBuilder.Entity("Vendas.Api.Models.PedidoItemAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdicionalId")
                        .HasColumnType("int")
                        .HasColumnName("adicionalId");

                    b.Property<int>("PedidoItemId")
                        .HasColumnType("int")
                        .HasColumnName("pedidoItemId");

                    b.HasKey("Id");

                    b.HasIndex("AdicionalId");

                    b.HasIndex("PedidoItemId");

                    b.ToTable("pedidoItemAdicional", (string)null);
                });

            modelBuilder.Entity("Vendas.Api.Models.PedidoItemSabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoItemId")
                        .HasColumnType("int");

                    b.Property<int>("SaborId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoItemId");

                    b.HasIndex("SaborId");

                    b.ToTable("pedidoItemSabor", (string)null);
                });

            modelBuilder.Entity("Vendas.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("Vendas.Api.Models.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descricao");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag");

                    b.Property<decimal>("Tipo")
                        .HasColumnType("numeric")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titulo");

                    b.Property<decimal>("ValorAdicional")
                        .HasColumnType("numeric")
                        .HasColumnName("valorAdicional");

                    b.HasKey("Id");

                    b.ToTable("sabor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Mussarela e azeitonas",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "Mussarela",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Mussarela, fatias de tomate e parmesão",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "Napolitana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Mussarela, tomate, manjericão fresco e parmesão",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "Marguerita",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Mussarela, fatias de tomate, peperone, manjericão e parmesão",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "Marguerita com Peperone",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Catupiry legítimo e azeitonas",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "Catupiry Legítimo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Mussarela e catupiry legítimo",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "2 Queijos",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Mussarela, catupiry legítimo e provolone",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "3 Queijos",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Mussarela, catupiry legítimo, provolone e parmesão",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "4 Queijos",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Mussarela, catupiry legítimo, provolone, parmesão e gorgonzola",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "5 Queijos",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Mussarela, parmesão e alho frito",
                            Tag = "queijo",
                            Tipo = 1m,
                            Titulo = "Pomodoro",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Frango, milho e mussarela",
                            Tag = "frango",
                            Tipo = 1m,
                            Titulo = "Frango com Mussarela",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Frango temperado com catupiry legítimo",
                            Tag = "frango",
                            Tipo = 1m,
                            Titulo = "Frango com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Frango temperado, bacon frito e provolone",
                            Tag = "frango",
                            Tipo = 1m,
                            Titulo = "Frango com Provolone",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Filé de frango temperado, milho no vapor e catupiry legítimo",
                            Tag = "frango",
                            Tipo = 1m,
                            Titulo = "Caipira",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Frango, milho, ervilha e mussarela",
                            Tag = "frango",
                            Tipo = 1m,
                            Titulo = "Carijó",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Frango, bacon frito e mussarela",
                            Tag = "frango",
                            Tipo = 1m,
                            Titulo = "Jardineira",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Frango, bacon, palmito, tomate, catupiry e mussarela",
                            Tag = "frango",
                            Tipo = 1m,
                            Titulo = "Frango Especial",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Calabresa moída, pimenta, ovos cozidos e cebola",
                            Tag = "calabresa",
                            Tipo = 1m,
                            Titulo = "Baiana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Calabresa moída, tomate, cebola e parmesão",
                            Tag = "calabresa",
                            Tipo = 1m,
                            Titulo = "Baiana Especial",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 20,
                            Descricao = "Calabresa fatiada, cebola e azeitonas",
                            Tag = "calabresa",
                            Tipo = 1m,
                            Titulo = "Calabresa",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 21,
                            Descricao = "Calabresa fatiada e mussarela",
                            Tag = "calabresa",
                            Tipo = 1m,
                            Titulo = "Calabresa com Mussarela",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 22,
                            Descricao = "Calabresa fatiada, cebola e catupiry legítimo",
                            Tag = "calabresa",
                            Tipo = 1m,
                            Titulo = "Calabresa com Catupiry Legítimo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 23,
                            Descricao = "Calabresa moída e mussarela",
                            Tag = "calabresa",
                            Tipo = 1m,
                            Titulo = "Toscana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 24,
                            Descricao = "Calabresa moída, ovos cozidos, cebola e mussarela",
                            Tag = "calabresa",
                            Tipo = 1m,
                            Titulo = "Toscana Especial",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 25,
                            Descricao = "Atum sólido, cebola e azeitonas",
                            Tag = "peixe",
                            Tipo = 1m,
                            Titulo = "Atum",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 26,
                            Descricao = "Atum sólido, cebola, tomate e catupiry legítimo",
                            Tag = "peixe",
                            Tipo = 1m,
                            Titulo = "Atum com Catupiry Legítimo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 27,
                            Descricao = "Atum sólido, cebola, tomate e mussarela",
                            Tag = "peixe",
                            Tipo = 1m,
                            Titulo = "Atum com Mussarela",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 28,
                            Descricao = "Atum sólido, bacon, cebola, ovos cozidos e mussarela",
                            Tag = "peixe",
                            Tipo = 1m,
                            Titulo = "Brasileira",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 29,
                            Descricao = "Atum sólido, palmito e mussarela",
                            Tag = "peixe",
                            Tipo = 1m,
                            Titulo = "Americana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 30,
                            Descricao = "Atum sólido, palmito, ervilha e mussarela",
                            Tag = "peixe",
                            Tipo = 1m,
                            Titulo = "Espanhola",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 31,
                            Descricao = "Brócolis, atum e cobertura de mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Bella Castelli",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 32,
                            Descricao = "Mussarela de búfala, tomate seco e rúcula",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Tomate Seco",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 33,
                            Descricao = "Mussarela, tomate seco e rúcula",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Rúcula",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 34,
                            Descricao = "Mussarela, peperone Sadia e parmesão",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Peperone",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 35,
                            Descricao = "Brócolis, bacon e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Brócolis",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 36,
                            Descricao = "Brócolis, palmito e catupiry legítimo",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Brócolis com Catupiry Legítimo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 37,
                            Descricao = "Champignon temperado, bacon e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Champignon",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 38,
                            Descricao = "Carne seca, tomate, cebola e mussarela com toque de pimenta biquinho",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Carne Seca",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 39,
                            Descricao = "Escarola, bacon e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Escarola com Bacon",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 40,
                            Descricao = "Mussarela, abacaxi em calda, hortelã e toque de canela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Doce de Cid",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 41,
                            Descricao = "Escarola, palmito, tomate, alho e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Escarola Especial",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 42,
                            Descricao = "Molho de tomate, parmesão e alho frito",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Alho",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 43,
                            Descricao = "Milho coberto com mussarela e orégano",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Milho com Mussarela",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 44,
                            Descricao = "Milho coberto com catupiry legítimo",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Milho com Catupiry Legítimo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 45,
                            Descricao = "Palmito fatiado com cobertura de mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Palmito",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 46,
                            Descricao = "Champignon temperado, bacon, mussarela e alho frito",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Siciliana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 47,
                            Descricao = "Calabresa moída, frango, tomate e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "À Moda da Casa",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 48,
                            Descricao = "Presunto, ovos cozidos, ervilhas, cebola e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Portuguesa",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 49,
                            Descricao = "Presunto, palmito, pimentão, cebola e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Paulista",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 50,
                            Descricao = "Presunto, ovos cozidos, bacon e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Cowboy",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 51,
                            Descricao = "1/4 Calabresa, 1/4 Mussarela, 1/4 Frango com catupiry e 1/4 Portuguesa",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Do Pizzaiolo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 52,
                            Descricao = "Presunto, tomate e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Bauru",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 53,
                            Descricao = "Calabresa fatiada, bacon, ovos, tomate e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Calabria",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 54,
                            Descricao = "Molho de tomate, selecionado, parmesão e azeitonas",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Aliche",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 55,
                            Descricao = "Bacon frito e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Bacon I",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 56,
                            Descricao = "Presunto, ovos, cebola e bacon",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Bacon II",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 57,
                            Descricao = "Presunto canadense, bacon e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Italiana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 58,
                            Descricao = "Lombo tipo canadense e mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Lombo com Mussarela",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 59,
                            Descricao = "Lombo tipo canadense e catupiry legítimo",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Lombo com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 60,
                            Descricao = "Lombo tipo canadense, bacon, milho e provolone",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Padrão",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 61,
                            Descricao = "Peito de peru, bacon frito, azeitonas e catupiry legítimo",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Peruana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 62,
                            Descricao = "Peito de peru, tomate, mussarela",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Peruana com Mussarela",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 63,
                            Descricao = "Peito de peru, palmito, cebola e catupiry legítimo",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Francesa",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 64,
                            Descricao = "Abobrinha, mussarela e alho frito",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Abobrinha",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 65,
                            Descricao = "Abobrinha, alho poró, parmesão e cream cheese",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Abobrinha Especial",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 66,
                            Descricao = "Brócolis, bacon, cebola e cream cheese",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Brócolis Especial",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 67,
                            Descricao = "Peito de peru e cream cheese",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Philadelphia",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 68,
                            Descricao = "Frango, bacon e cream cheese",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Frango c/ Cream Cheese",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 69,
                            Descricao = "Filé mignon, mussarela, cebola, catupiry e alho frito salpicado",
                            Tag = "especial",
                            Tipo = 1m,
                            Titulo = "Filé Mignon",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 80,
                            Descricao = "Morango, chocolate e leite condensado",
                            Tag = "doce",
                            Tipo = 1m,
                            Titulo = "Morango",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 81,
                            Descricao = "Chocolate, banana com canela e leite condensado",
                            Tag = "doce",
                            Tipo = 1m,
                            Titulo = "Banana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 82,
                            Descricao = "Chocolate, banana, canela e leite condensado",
                            Tag = "doce",
                            Tipo = 1m,
                            Titulo = "Banana com Chocolate",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 83,
                            Descricao = "Chocolate e granulado",
                            Tag = "doce",
                            Tipo = 1m,
                            Titulo = "Chocolate",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 84,
                            Descricao = "Nutella, castanha ou frutas (morango ou banana)",
                            Tag = "doce",
                            Tipo = 1m,
                            Titulo = "Nutella",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 85,
                            Descricao = "Nutella e M&M’s",
                            Tag = "doce",
                            Tipo = 1m,
                            Titulo = "Nutella com MM’s",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 86,
                            Descricao = "Chocolate e M&M’s",
                            Tag = "doce",
                            Tipo = 1m,
                            Titulo = "Chocolate com MM’s",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 87,
                            Descricao = "Nutella com castanha",
                            Tag = "doce",
                            Tipo = 1m,
                            Titulo = "Nutella com Castanha",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 88,
                            Descricao = "Esfiha aberta de carne temperada",
                            Tag = "carne",
                            Tipo = 2m,
                            Titulo = "Carne",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 89,
                            Descricao = "Esfiha aberta com queijo derretido",
                            Tag = "queijo",
                            Tipo = 2m,
                            Titulo = "Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 90,
                            Descricao = "Calabresa fatiada e levemente apimentada",
                            Tag = "calabresa",
                            Tipo = 2m,
                            Titulo = "Calabresa",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 91,
                            Descricao = "Frango desfiado com catupiry cremoso",
                            Tag = "frango",
                            Tipo = 2m,
                            Titulo = "Frango com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 92,
                            Descricao = "Presunto, queijo e tomate",
                            Tag = "presunto",
                            Tipo = 2m,
                            Titulo = "Bauru",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 93,
                            Descricao = "Atum temperado com leve toque de limão",
                            Tag = "atum",
                            Tipo = 2m,
                            Titulo = "Atum",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 94,
                            Descricao = "Atum temperado e queijo derretido",
                            Tag = "atum",
                            Tipo = 2m,
                            Titulo = "Atum com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 95,
                            Descricao = "Palmito picado com queijo",
                            Tag = "palmito",
                            Tipo = 2m,
                            Titulo = "Palmito com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 96,
                            Descricao = "Palmito com catupiry cremoso",
                            Tag = "palmito",
                            Tipo = 2m,
                            Titulo = "Palmito com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 97,
                            Descricao = "Escarola refogada com queijo",
                            Tag = "vegetariana",
                            Tipo = 2m,
                            Titulo = "Escarola com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 98,
                            Descricao = "Calabresa e queijo derretido",
                            Tag = "calabresa",
                            Tipo = 2m,
                            Titulo = "Calabresa com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 99,
                            Descricao = "Calabresa com catupiry cremoso",
                            Tag = "calabresa",
                            Tipo = 2m,
                            Titulo = "Calabresa com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 100,
                            Descricao = "Milho verde com queijo derretido",
                            Tag = "vegetariana",
                            Tipo = 2m,
                            Titulo = "Milho com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 101,
                            Descricao = "Milho verde com catupiry",
                            Tag = "vegetariana",
                            Tipo = 2m,
                            Titulo = "Milho Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 102,
                            Descricao = "Bacon crocante e queijo derretido",
                            Tag = "bacon",
                            Tipo = 2m,
                            Titulo = "Bacon com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 103,
                            Descricao = "Mistura de queijos derretidos",
                            Tag = "queijo",
                            Tipo = 2m,
                            Titulo = "Dois Queijos",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 104,
                            Descricao = "Carne temperada com queijo",
                            Tag = "carne",
                            Tipo = 2m,
                            Titulo = "Carne com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 105,
                            Descricao = "Brócolis refogado com queijo",
                            Tag = "vegetariana",
                            Tipo = 2m,
                            Titulo = "Brócolis com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 106,
                            Descricao = "Pepperone levemente picante com queijo",
                            Tag = "pepperone",
                            Tipo = 2m,
                            Titulo = "Pepperone",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 107,
                            Descricao = "Carne seca desfiada com queijo",
                            Tag = "carne",
                            Tipo = 2m,
                            Titulo = "Carne Seca com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 108,
                            Descricao = "Carne seca desfiada com catupiry",
                            Tag = "carne",
                            Tipo = 2m,
                            Titulo = "Carne Seca com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 109,
                            Descricao = "Esfiha aberta apenas com catupiry",
                            Tag = "queijo",
                            Tipo = 2m,
                            Titulo = "Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 110,
                            Descricao = "Esfiha aberta de carne temperada",
                            Tag = "carne",
                            Tipo = 2m,
                            Titulo = "Carne",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 111,
                            Descricao = "Esfiha aberta com queijo derretido",
                            Tag = "queijo",
                            Tipo = 2m,
                            Titulo = "Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 112,
                            Descricao = "Calabresa fatiada e levemente apimentada",
                            Tag = "calabresa",
                            Tipo = 2m,
                            Titulo = "Calabresa",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 113,
                            Descricao = "Frango desfiado com catupiry cremoso",
                            Tag = "frango",
                            Tipo = 2m,
                            Titulo = "Frango com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 114,
                            Descricao = "Presunto, queijo e tomate",
                            Tag = "presunto",
                            Tipo = 2m,
                            Titulo = "Bauru",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 115,
                            Descricao = "Atum temperado com leve toque de limão",
                            Tag = "atum",
                            Tipo = 2m,
                            Titulo = "Atum",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 116,
                            Descricao = "Atum temperado e queijo derretido",
                            Tag = "atum",
                            Tipo = 2m,
                            Titulo = "Atum com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 117,
                            Descricao = "Palmito picado com queijo",
                            Tag = "palmito",
                            Tipo = 2m,
                            Titulo = "Palmito com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 118,
                            Descricao = "Palmito com catupiry cremoso",
                            Tag = "palmito",
                            Tipo = 2m,
                            Titulo = "Palmito com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 119,
                            Descricao = "Escarola refogada com queijo",
                            Tag = "vegetariana",
                            Tipo = 2m,
                            Titulo = "Escarola com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 120,
                            Descricao = "Calabresa e queijo derretido",
                            Tag = "calabresa",
                            Tipo = 2m,
                            Titulo = "Calabresa com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 121,
                            Descricao = "Calabresa com catupiry cremoso",
                            Tag = "calabresa",
                            Tipo = 2m,
                            Titulo = "Calabresa com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 122,
                            Descricao = "Milho verde com queijo derretido",
                            Tag = "vegetariana",
                            Tipo = 2m,
                            Titulo = "Milho com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 123,
                            Descricao = "Milho verde com catupiry",
                            Tag = "vegetariana",
                            Tipo = 2m,
                            Titulo = "Milho Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 124,
                            Descricao = "Bacon crocante e queijo derretido",
                            Tag = "bacon",
                            Tipo = 2m,
                            Titulo = "Bacon com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 125,
                            Descricao = "Mistura de queijos derretidos",
                            Tag = "queijo",
                            Tipo = 2m,
                            Titulo = "Dois Queijos",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 126,
                            Descricao = "Carne temperada com queijo",
                            Tag = "carne",
                            Tipo = 2m,
                            Titulo = "Carne com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 127,
                            Descricao = "Brócolis refogado com queijo",
                            Tag = "vegetariana",
                            Tipo = 2m,
                            Titulo = "Brócolis com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 128,
                            Descricao = "Pepperone levemente picante com queijo",
                            Tag = "pepperone",
                            Tipo = 2m,
                            Titulo = "Pepperone",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 129,
                            Descricao = "Carne seca desfiada com queijo",
                            Tag = "carne",
                            Tipo = 2m,
                            Titulo = "Carne Seca com Queijo",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 130,
                            Descricao = "Carne seca desfiada com catupiry",
                            Tag = "carne",
                            Tipo = 2m,
                            Titulo = "Carne Seca com Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 131,
                            Descricao = "Esfiha aberta apenas com catupiry",
                            Tag = "queijo",
                            Tipo = 2m,
                            Titulo = "Catupiry",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 132,
                            Descricao = "Chocolate cremoso com granulado",
                            Tag = "chocolate",
                            Tipo = 2m,
                            Titulo = "Chocolate com Granulado",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 133,
                            Descricao = "Chocolate com pedaços de morango",
                            Tag = "chocolate",
                            Tipo = 2m,
                            Titulo = "Chocolate com Morango",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 134,
                            Descricao = "Chocolate com rodelas de banana",
                            Tag = "chocolate",
                            Tipo = 2m,
                            Titulo = "Chocolate com Banana",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 135,
                            Descricao = "Esfiha doce recheada com Nutella",
                            Tag = "nutella",
                            Tipo = 2m,
                            Titulo = "Nutella",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 136,
                            Descricao = "Nutella com cobertura de M&M's",
                            Tag = "nutella",
                            Tipo = 2m,
                            Titulo = "Nutella com M&M's",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 137,
                            Descricao = "Chocolate cremoso com M&M's",
                            Tag = "chocolate",
                            Tipo = 2m,
                            Titulo = "Chocolate com M&M's",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 138,
                            Descricao = "Banana com cobertura de leite condensado",
                            Tag = "banana",
                            Tipo = 2m,
                            Titulo = "Banana com Leite Condensado",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 139,
                            Descricao = "Chocolate com pedaços de castanha",
                            Tag = "chocolate",
                            Tipo = 2m,
                            Titulo = "Chocolate com Castanha",
                            ValorAdicional = 0m
                        },
                        new
                        {
                            Id = 140,
                            Descricao = "Nutella com castanhas crocantes",
                            Tag = "nutella",
                            Tipo = 2m,
                            Titulo = "Nutella com Castanha",
                            ValorAdicional = 0m
                        });
                });

            modelBuilder.Entity("Vendas.Api.Models.Tamanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("numeric")
                        .HasColumnName("valorBase");

                    b.HasKey("Id");

                    b.ToTable("tamanho", (string)null);
                });

            modelBuilder.Entity("Vendas.Api.Models.Pedido", b =>
                {
                    b.HasOne("Vendas.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vendas.Api.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("Vendas.Api.Models.PedidoItem", b =>
                {
                    b.HasOne("Vendas.Api.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vendas.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vendas.Api.Models.Tamanho", "Tamanho")
                        .WithMany()
                        .HasForeignKey("TamanhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("Tamanho");
                });

            modelBuilder.Entity("Vendas.Api.Models.PedidoItemAdicional", b =>
                {
                    b.HasOne("Vendas.Api.Models.Adicional", "Adicional")
                        .WithMany()
                        .HasForeignKey("AdicionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vendas.Api.Models.PedidoItem", "PedidoItem")
                        .WithMany("Adicionais")
                        .HasForeignKey("PedidoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adicional");

                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("Vendas.Api.Models.PedidoItemSabor", b =>
                {
                    b.HasOne("Vendas.Api.Models.PedidoItem", "PedidoItem")
                        .WithMany("Sabores")
                        .HasForeignKey("PedidoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vendas.Api.Models.Sabor", "Sabor")
                        .WithMany()
                        .HasForeignKey("SaborId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoItem");

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("Vendas.Api.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Vendas.Api.Models.PedidoItem", b =>
                {
                    b.Navigation("Adicionais");

                    b.Navigation("Sabores");
                });
#pragma warning restore 612, 618
        }
    }
}
